#include "menus/menu.h"

#define NOSQ_SPECIALS_AMNT 18

enum NoSQPracticeIndex {
    NOSQ_BOKO_PUSH_INDEX,
    NOSQ_HUGO_INDEX,
    NOSQ_FARON_TWILIGHT_INDEX,
    // NOSQ_EMS_INDEX,
    NOSQ_FOREST_TEMPLE_INDEX,
    NOSQ_EARLY_RANG_INDEX,
    NOSQ_FRST_ESCAPE_INDEX,
    NOSQ_GORGE_VOID_INDEX,
    NOSQ_RUPEE_ROLL_INDEX,
    NOSQ_ELDIN_TWILIGHT_INDEX,
    // NOSQ_BOMB_HOUSE_SKIP_INDEX,
    // NOSQ_POST_ELDIN_INDEX,
    NOSQ_LANAYRU_GATE_CLIP_INDEX,
    // NOSQ_KARG_INDEX,
    NOSQ_LANAYRU_TWILIGHT_INDEX,
    // NOSQ_WATERFALL_SIDEHOP_INDEX,
    // NOSQ_BOSS_BUG_INDEX,
    NOSQ_KB2_SKIP_INDEX,
    NOSQ_ESCORT_INDEX,
    NOSQ_PILLAR_CLIP_INDEX,
    NOSQ_LAKEBED_INDEX,
    // NOSQ_TOAD_INDEX,
    NOSQ_LAKEBED_BK_SKIP_INDEX,
    NOSQ_MORPHEEL_INDEX,
    // NOSQ_MDH_INDEX,
    // NOSQ_MOUNTAIN_INDEX,
    NOSQ_SPR_WARP_SKIP_INDEX,
    NOSQ_SPR_INDEX,
    // NOSQ_BULBLIN_CAMP_INDEX,
    NOSQ_AG_INDEX,
    // NOSQ_POE_1_SKIP_INDEX,
    NOSQ_DS_INDEX,
    NOSQ_STALLORD_INDEX,
    // NOSQ_CITS_EARLY_INDEX,
    NOSQ_CITS_1_INDEX,
    NOSQ_AERALFOS_SKIP_INDEX,
    NOSQ_CITS_2_INDEX,
    // NOSQ_FAN_TOWER_INDEX,
    NOSQ_ARGOROK_INDEX,
    NOSQ_PALACE_1_INDEX,
    NOSQ_PALACE_2_INDEX,
    NOSQ_ZANT_INDEX,
    NOSQ_HC_INDEX,
    // NOSQ_HC_INSIDE_INDEX,
    // NOSQ_BEAST_GANON_INDEX,
    // NOSQ_HORSEBACK_GANON_INDEX,

    // Entry used as a count of entries
    NOSQ_SAVES_COUNT
};

class NoSQSavesMenu : public Menu {
public:
    NoSQSavesMenu(Cursor& cursor);
    virtual ~NoSQSavesMenu();
    virtual void draw();

private:
    Line lines[NOSQ_SAVES_COUNT];
};