#include "menus/menu.h"

#ifdef GCN_PLATFORM
#define ANY_BITE_SPECIALS_AMNT 18

enum AnyBiTEPracticeIndex {
    BITE_ORDON_GATE_CLIP_INDEX,
    BITE_BACK_IN_TIME_INDEX,
    BITE_GOATS_INDEX,
    BITE_HUGO_INDEX,
    BITE_FARON_TWILIGHT_INDEX,
    BITE_EMS_INDEX,
    BITE_MIST_INDEX,
    BITE_FRST_BIT_INDEX,
    BITE_FRST_ESCAPE_INDEX,
    BITE_LANAYRU_GATE_CLIP_INDEX,
    BITE_PILLAR_CLIP_INDEX,
    BITE_LAKEBED_1_INDEX,
    BITE_TOAD_INDEX,
    BITE_KARG_INDEX,
    BITE_KB1_INDEX,
    BITE_ELDIN_TWILIGHT_INDEX,
    BITE_LANAYRU_TWILIGHT_INDEX,
    BITE_WATERFALL_SIDEHOP_INDEX,
    BITE_IZA_INDEX,
    BITE_SPR_WARP_SKIP_INDEX,
    BITE_SPR_INDEX,
    BITE_DARK_HAMMER_INDEX,
    BITE_LAKEBED_BK_SKIP_INDEX,
    BITE_ONEBOMB_INDEX,
    BITE_MDH_TOWER_INDEX,
    BITE_MDH_BRIDGE_INDEX,
    BITE_BULBLIN_CAMP_INDEX,
    BITE_AG_INDEX,
    BITE_PGS_INDEX,
    BITE_DSS_INDEX,
    BITE_STALLORD_INDEX,
    BITE_STALLORD2_INDEX,
    BITE_SILVER_RUPEE,
    BITE_CITS_EARLY_INDEX,
    BITE_CITS_1_INDEX,
    BITE_AERALFOS_SKIP_INDEX,
    BITE_FAN_TOWER_INDEX,
    BITE_ARGOROK_INDEX,
    BITE_PALACE_1_INDEX,
    BITE_PALACE_2_INDEX,
    BITE_EARLY_PLATFORM_INDEX,
    BITE_ZANT_INDEX,
    BITE_HC_INDEX,
    BITE_HC_TOWER_INDEX,
    BITE_BEAST_GANON_INDEX,
    BITE_HORSEBACK_GANON_INDEX,

    // Entry used as a count of entries
    ANY_BITE_SAVES_COUNT
};
#endif
#ifdef WII_PLATFORM
#define ANY_BITE_SPECIALS_AMNT 13

enum AnyBiTEPracticeIndex {
    BITE_ORDON_GATE_CLIP_INDEX,
    BITE_BACK_IN_TIME_INDEX,
    BITE_SEAM_CLIP_INDEX,
    BITE_GOATS_INDEX,
    BITE_HUGO_INDEX,
    BITE_FARON_TWILIGHT_INDEX,
    BITE_EMS_INDEX,
    BITE_MIST_INDEX,
    BITE_KB1_INDEX,
    BITE_ELDIN_TWILIGHT_INDEX,
    BITE_BOMBHOUSE_SKIP_INDEX,
    BITE_EPONA_OOB_INDEX,
    BITE_LANAYRU_TWILIGHT_INDEX,
    BITE_WATERFALL_SIDEHOP_INDEX,
    BITE_BOSS_BUG_INDEX,
    BITE_IZA_INDEX,
    BITE_PLUMM_OOB_INDEX,
    BITE_ENTER_LAKEBED_INDEX,
    BITE_LAKEBED_1_INDEX,
    BITE_TOAD_INDEX,
    BITE_ONEBOMB_INDEX,
    BITE_MDH_TOWER_INDEX,
    BITE_MDH_BRIDGE_INDEX,
    BITE_MESSENGER_SKIP_INDEX,
    BITE_SPR_MBBB_INDEX,
    BITE_FREEZARD_SKIP_INDEX,
    BITE_DARK_HAMMER_INDEX,
    BITE_BULBLIN_CAMP_INDEX,
    BITE_AG_INDEX,
    BITE_PGS_INDEX,
    BITE_EARLY_BOSS_KEY_INDEX,
    BITE_DSS_INDEX,
    BITE_STALLORD_INDEX,
    BITE_STALLORD2_INDEX,
    BITE_CITS_EARLY_INDEX,
    BITE_CITS_1_INDEX,
    BITE_AERALFOS_SKIP_INDEX,
    BITE_CITS_2_INDEX,
    BITE_FAN_TOWER_INDEX,
    BITE_ARGOROK_INDEX,
    BITE_PALACE_1_INDEX,
    BITE_STUPID_ROOM_INDEX,
    BITE_PALACE_2_INDEX,
    BITE_EARLY_PLATFORM_INDEX,
    BITE_ZANT_INDEX,
    BITE_HC_INDEX,
    BITE_DARKNUT_INDEX,
    BITE_HC_TOWER_INDEX,
    BITE_BEAST_GANON_INDEX,
    BITE_HORSEBACK_GANON_INDEX,

    // Entry used as a count of entries
    ANY_BITE_SAVES_COUNT
};
#endif

class AnyBiTESavesMenu : public Menu {
public:
    AnyBiTESavesMenu(Cursor& cursor);
    virtual ~AnyBiTESavesMenu();
    virtual void draw();

private:
    Line lines[ANY_BITE_SAVES_COUNT];
};