#ifndef LIB_TP_WARPING
#define LIB_TP_WARPING
enum CaveStage {
    LanayruIcePuzzleCave,
    CaveOfOrdeals,
    EldinLongCave,
    LakeHyliaLongCave,
    EldinGoronStockcave,
    Grotto1,
    Grotto2,
    Grotto3,
    Grotto4,
    Grotto5,
    FaronWoodsCave,
};

enum DungeonStage {
    LakebedTemple,
    Morpheel,
    DekuToad,
    GoronMines,
    Fyrus,
    Dangoro,
    ForestTemple,
    Diababa,
    Ook,
    TempleOfTime,
    Armogohma,
    Darknut,
    CityInTheSky,
    Argorok,
    Aeralfos,
    PalaceOfTwilight,
    ZantMainRoom,
    PhantomZant1,
    PhantomZant2,
    ZantFight,
    HyruleCastle,
    GanondorfCastle,
    GanondorfField,
    GanondorfDefeated,
    ArbitersGrounds,
    Stallord,
    DeathSword,
    SnowpeakRuins,
    Blizzeta,
    Darkhammer,
};

enum InteriorStage {
    OrdonVillage,
    HyruleCastleSewers,
    FaronWoods,
    KakarikoVillage,
    DeathMountain,
    TelmasBar,
    FishingPond,
    HiddenVillage,
    CastleTown,
    StarGame,
    KakarikoGraveyard,
    LightArrowsCutscene,
    HyruleCastleCutscenes,
};

enum OverworldStage {
    OrdonRanch,
    TitleScreen,
    OrdonVillage,
    OrdonSpring,
    FaronWoods,
    KakarikoVillage,
    DeathMountain,
    KakarikoGraveyard,
    ZorasRiver,
    ZorasDomain,
    Snowpeak,
    LakeHylia,
    CastleTown,
    SacredGrove,
    BublinCamp,
    HyruleField,
    OutsideCastleTown,
    Bublin2,
    GerudoDesert,
    MirrorChamber,
    UpperZorasRiver,
    FishingPond,
    HiddenVillage,
    HiddenSkill,
};

#endif