add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/libtp_c
    COMMAND COMMAND cp -r ${CMAKE_CURRENT_SOURCE_DIR}/external/libtp_c ${CMAKE_CURRENT_BINARY_DIR}/libtp_c
    BYPRODUCTS ${CMAKE_CURRENT_BINARY_DIR}/libtp_c)

add_custom_target(tp_c
    DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/libtp_c
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/libtp_c
    COMMAND make PLATFORM=${PLATFORM} REGION=${REGION}
    BYPRODUCTS ${CMAKE_CURRENT_BINARY_DIR}/libtp_c/libtp_c.a ${CMAKE_CURRENT_BINARY_DIR}/libtp_c/build)